/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fightcup;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.JSpinner;

/**
 *
 * @author Przemo
 */
public class TeamParamsPanel extends javax.swing.JPanel {

    enum SkillMode {
        ATACK,
        DEFENSE
    };
    
    /**
     * lista zawodnikow 
     */
    List<Fighter> teamFighters = new ArrayList<>();
    
    /**
     * Mapa element formularza - skill
     */
    Map<Fighter.Skill, JSpinner> skillElementMap = new HashMap<>();
    
    /**
     * model dla tabeli zawodnikow
     * 
     */
    Object[][] dataModel = {};
    
    public TeamParamsPanel(String title) { 
        setBorder(javax.swing.BorderFactory.createTitledBorder(
                null, 
                title, 
                javax.swing.border.TitledBorder.CENTER, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Calibri", 0, 18), 
                new java.awt.Color(102, 102, 102))); 
        initComponents();          
        
        // wypelnienie mapy        
        skillElementMap.put(Fighter.Skill.ATACK_BOXING, atackBoxingSpinner);
        skillElementMap.put(Fighter.Skill.ATACK_KICKING, atackKickingSpinner);
        skillElementMap.put(Fighter.Skill.ATACK_RUNNING_SPEED, atackRunningSpinner);
        
        skillElementMap.put(Fighter.Skill.DEFENSE_BOXING, defenseBoxingSpinner);
        skillElementMap.put(Fighter.Skill.DEFENSE_KICKING, defenseKickingSpinner);
        skillElementMap.put(Fighter.Skill.DEFENSE_RUNNING_SPEED, defenseRunningSpinner);
    }
        
    private void randomSkills() {
        Random generator = new Random();        
        for (JSpinner spinner : skillElementMap.values()) {
            int value = generator.nextInt(10);
            spinner.setValue(value);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        atackRunningSpinner = new javax.swing.JSpinner();
        defenseRunningSpinner = new javax.swing.JSpinner();
        defenseBoxingSpinner = new javax.swing.JSpinner();
        atackKickingSpinner = new javax.swing.JSpinner();
        atackBoxingSpinner = new javax.swing.JSpinner();
        defenseKickingSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fightersList = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jLabel3.setText("Boxing");

        jLabel4.setText("Kicking");

        jLabel5.setText("Running speed");

        atackRunningSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseRunningSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseBoxingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        atackKickingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        atackBoxingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseKickingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel2.setText("DEFENSE");

        jLabel1.setText("ATACK");

        jButton1.setText("Random values");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        fightersList.setModel(new javax.swing.table.DefaultTableModel(
            dataModel,
            new String [] {
                "#", "Boxing", "Kicking", "Running"
            }
        ));
        jScrollPane2.setViewportView(fightersList);

        jButton2.setText("Add");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(atackRunningSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atackKickingSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atackBoxingSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(defenseBoxingSpinner)
                                .addComponent(defenseKickingSpinner)
                                .addComponent(defenseRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atackBoxingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(defenseBoxingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atackKickingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(defenseKickingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atackRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(defenseRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        atackBoxingSpinner.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        randomSkills();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Fighter fighter = new Fighter();
        for (Fighter.Skill skill : skillElementMap.keySet()) {
            JSpinner spinner = skillElementMap.get(skill);
            fighter.setSkill(skill, Integer.parseInt(spinner.getValue().toString()));
        }
        teamFighters.add(fighter);
    }//GEN-LAST:event_jButton2MouseClicked

    private void updateFightersListModel() {
        int i = 1;
        dataModel = new Object[teamFighters.size()][4];
        for (Fighter fighter : teamFighters) {
            dataModel[i][0] = String.valueOf(i));
            dataModel[i][1] = String.format("%s/%s", 
                    fighter.getSkill(Fighter.Skill.ATACK_BOXING),
                    fighter.getSkill(Fighter.Skill.DEFENSE_BOXING));
            dataModel[i][2] = String.format("%s/%s", 
                    fighter.getSkill(Fighter.Skill.ATACK_KICKING),
                    fighter.getSkill(Fighter.Skill.DEFENSE_KICKING));
            dataModel[i][3] = String.format("%s/%s", 
                    fighter.getSkill(Fighter.Skill.ATACK_RUNNING_SPEED),
                    fighter.getSkill(Fighter.Skill.DEFENSE_RUNNING_SPEED));
        }
        fightersList.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner atackBoxingSpinner;
    private javax.swing.JSpinner atackKickingSpinner;
    private javax.swing.JSpinner atackRunningSpinner;
    private javax.swing.JSpinner defenseBoxingSpinner;
    private javax.swing.JSpinner defenseKickingSpinner;
    private javax.swing.JSpinner defenseRunningSpinner;
    private javax.swing.JTable fightersList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}

