/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fightcup;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import javax.swing.JSpinner;

/**
 *
 * @author Przemo
 */
public class TeamParamsPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeamConfig
     * @param title
     */
    public TeamParamsPanel(String title) {        
        setBorder(javax.swing.BorderFactory.createTitledBorder(
                null, 
                title, 
                javax.swing.border.TitledBorder.CENTER, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Calibri", 0, 18), 
                new java.awt.Color(102, 102, 102))); 
        initComponents();              
    }
    
    public Map<Fighter.Skill, Integer> getAtackSkillLevel() {
        Map<Fighter.Skill, Integer> skills = new HashMap<>();
        
        skills.put(Fighter.Skill.BOXING, Integer.parseInt(atackBoxingSpinner.getValue().toString()));
        skills.put(Fighter.Skill.KICKING, Integer.parseInt(atackKickingSpinner.getValue().toString()));
        skills.put(Fighter.Skill.RUNNING_SPEED, Integer.parseInt(atackRunningSpinner.getValue().toString()));
        
        return skills;
    }
    
    public Map<Fighter.Skill, Integer> getDefenseSkillLevel() {
        Map<Fighter.Skill, Integer> skills = new HashMap<>();
        
        skills.put(Fighter.Skill.BOXING, Integer.parseInt(defenseBoxingSpinner.getValue().toString()));
        skills.put(Fighter.Skill.KICKING, Integer.parseInt(defenseKickingSpinner.getValue().toString()));
        skills.put(Fighter.Skill.RUNNING_SPEED, Integer.parseInt(defenseRunningSpinner.getValue().toString()));
        
        return skills;
    }
    
    private void randomSkills() {
        Random generator = new Random();
        List<JSpinner> list = new ArrayList<>();
        list.add(atackBoxingSpinner);
        list.add(atackKickingSpinner);
        list.add(atackRunningSpinner);
        list.add(defenseBoxingSpinner);
        list.add(defenseKickingSpinner);
        list.add(defenseRunningSpinner);
        
        for (JSpinner spinner : list) {            
            spinner.setValue(generator.nextInt(10) );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        atackRunningSpinner = new javax.swing.JSpinner();
        defenseRunningSpinner = new javax.swing.JSpinner();
        defenseBoxingSpinner = new javax.swing.JSpinner();
        atackKickingSpinner = new javax.swing.JSpinner();
        atackBoxingSpinner = new javax.swing.JSpinner();
        defenseKickingSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("Boxing");

        jLabel4.setText("Kicking");

        jLabel5.setText("Running speed");

        atackRunningSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseRunningSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseBoxingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        atackKickingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        atackBoxingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        defenseKickingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel2.setText("DEFENSE");

        jLabel1.setText("ATACK");

        jButton1.setText("Random values");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(atackRunningSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atackKickingSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atackBoxingSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(defenseBoxingSpinner)
                                .addComponent(defenseKickingSpinner)
                                .addComponent(defenseRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atackBoxingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(defenseBoxingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atackKickingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(defenseKickingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atackRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(defenseRunningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        atackBoxingSpinner.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        randomSkills();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner atackBoxingSpinner;
    private javax.swing.JSpinner atackKickingSpinner;
    private javax.swing.JSpinner atackRunningSpinner;
    private javax.swing.JSpinner defenseBoxingSpinner;
    private javax.swing.JSpinner defenseKickingSpinner;
    private javax.swing.JSpinner defenseRunningSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
